server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.97.170.253:3306/bbs?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    username: 614714303@qq.com
    #授权码
    password: tgalsufbhplpbfcd
    #安全处理
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          ssl:
            trust: smtp.qq.com
          auth: true
          starttls:
            enable: true
            required: true
        imap:
          ssl:
            socketFactory:
              fallback: false

    port: 465
    host: smtp.qq.com
pagehelper:
  helper-dialect: mysql